### ISSUE TITLE
Input interface of example.txt not specified

### ISSUE THREAD

**Issue by Brian-Yee** [IoannisPapageorgiou/Bayesian-Context-Trees#1]
Hello, 

I came across this repo after reading the related paper however it is unclear to me what the format of `example.txt` should be. While the file is read in to variable `xn` which suggests to me that it should be of the form outlined in section 3.1 of [the paper](https://arxiv.org/pdf/2007.14900.pdf) I cannot infer outside of random guessing what the input format of `example.txt` should be.

Can you please upload an example `example.txt` or specify the format expected of `example.txt` in the `README.md`?

Cheers,
Brian

**Comment by IoannisPapageorgiou** [comment]
Hi,

Thanks for your comments, I guess the input format of example.txt wasn't 
properly specified.

I 've now added a simple example with a ternary dataset in the 
repository. As it is, the input format is a simple text file with the 
characters one after the other. (You can also use the function read2 
instead of read if you want to read from a file that has each symbol in 
a new line, but this shouldn't be necessary with small alphabets).


Also, I added a comment sayng that the vector "xn" should be the whole 
dataset x_{-D+1}^n as specified in section 3.1 of the paper.


I hope these changes make clear the format of the input "example.txt". 
Again, thanks for the feedback and feel free to get in contact if you 
have any futher questions/suggestions.

Best,

Ioannis

**Comment by Brian-Yee** [comment]
Thanks for specifying the interface along with `read2` capabilities. All seems to be working now. Will reach out if there are any further questions/suggestions.

Best regards,
Brian
